<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYextKij\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYextKij/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYextKij.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYextKij\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYextKij\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YextKij',
    'container.build_id' => 'aa9d6c37',
    'container.build_time' => 1563967765,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYextKij');
